!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

' System Configs
AddElementTag("t1", $legendText="T1 - Tier 1 System", $bgColor="#F4CCD2", $borderColor="#B7B5BA", $fontColor="#390008")
AddElementTag("t2", $legendText="T2 - Tier 2 System", $bgColor="#FDFACE", $borderColor="#B7B5BA", $fontColor="#312E02")
AddElementTag("t3", $legendText="T3 - Tier 3 System", $bgColor="#D9F7E6", $borderColor="#B7B5BA", $fontColor="#0D2B1A")

UpdateElementStyle("boundary", $shadowing="true")

' Style
skinparam RoundCorner 15
' Change the Font Size
' skinparam DefaultFontSize 10
' Change the Font Family Name
' skinparam DefaultFontName "Open Sans Light"
' skinparam DefaultFontName "Georgia,serif"
skinparam DefaultFontName "Helvetica Neue, Helvetica, Arial, sans-serif"
' Change the definition/size
skinparam dpi 150
' Controls the padding surrounding text
' skinparam padding 3
